apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-async-rabbitmq
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: async-rabbitmq
spec:
  type: {{ .Values.asyncRabbitmq.service.type }}
  ports:
    - port: {{ .Values.asyncRabbitmq.service.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.asyncRabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: async-rabbitmq
