{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bind9.fullname" . }}
  labels:
    {{- include "bind9.labels" . | nindent 4 }}
spec:
  endpoints:
    {{ .Values.metrics.serviceMonitor.endpoints | toYaml | nindent 4 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "bind9.selectorLabels" . | nindent 6 }}
{{- end }}
