apiVersion: v2
name: taiga
description: A helm chart for Taiga.io, an open-source project management platform for agile teams
type: application
version: 2026.3.6
appVersion: "6.9.0"
icon: https://avatars.githubusercontent.com/u/6905422?s=200&v=4

sources:
  - https://taiga.io/
  - https://github.com/taigaio/taiga-docker

keywords:
  - taiga
  - kanban
  - project
  - management
  - task
  - board
  - collaboration
  - live

maintainers:
  - name: David Gheghea
    email: david.gheghea@unxwares.com
    url: https://github.com/UnxWares

annotations:
  category: tools
  artifacthub.io/license: "MIT"
