apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taiga.fullname" . }}-frontend
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taiga.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "taiga.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.frontend.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taiga.serviceAccountName" . }}
      {{- with (default .Values.global.podSecurityContext .Values.frontend.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          {{- with (default .Values.global.securityContext .Values.frontend.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and .Values.global.oidc.enabled .Values.global.oidc.frontend.overrideImage.name }}
          image: "{{ .Values.global.oidc.frontend.overrideImage.name }}:{{ .Values.global.oidc.frontend.overrideImage.tag }}"
          {{- else }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            {{- include "taiga.frontendEnv" . | nindent 12 }}
            {{- with .Values.frontend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or .Values.global.extraEnvFrom .Values.frontend.extraEnvFrom }}
          envFrom:
            {{- with .Values.global.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.frontend.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
            {{- with $.Values.global.defaultProbes.liveness }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
            {{- with $.Values.global.defaultProbes.readiness }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
          {{- end }}
          {{- with (default .Values.global.resources .Values.frontend.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.frontend.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.pod.nodeSelector .Values.frontend.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.pod.affinity .Values.frontend.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.pod.tolerations .Values.frontend.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
