apiVersion: v2
name: bind9
description: A flexible and production-ready Helm chart for running ISC Bind9 DNS server on Kubernetes.
type: application

version: 2026.2.21
appVersion: "9.21"
icon: https://www.aschnoebelen.fr/wp-content/uploads/2024/01/bind9.png

sources:
  - https://github.com/isc-projects/bind9
  - https://hub.docker.com/r/internetsystemsconsortium/bind9
  - https://github.com/UnxWare/helm

keywords:
  - dns
  - bind
  - bind9
  - authoritative-dns
  - kubernetes
  - helm
  - network

maintainers:
  - name: David Gheghea
    email: david.gheghea@unxwares.com
    url: https://github.com/UnxWares
  - name: Baptiste Gosselin
    email: baptiste.gosselin@unxwares.com
    url: https://github.com/UnxWares

annotations:
  category: networking
  artifacthub.io/license: "MIT"
  artifacthub.io/links: |
    [
      { "name": "Upstream", "url": "https://www.isc.org/bind/" }
    ]
