apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-events-rabbitmq
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: events-rabbitmq
spec:
  type: {{ .Values.eventsRabbitmq.service.type }}
  ports:
    - port: {{ .Values.eventsRabbitmq.service.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.eventsRabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: events-rabbitmq
